export const layoutRegistry = [
  {
    id: 'original',
    name: 'Original Layout',
    description: 'The current handcrafted homepage. Sketch/hand-drawn aesthetic with warm personality.',
    theme: 'Sketch / handwritten',
    font: 'Inter + Architects Daughter',
    colors: ['#0B1F3A', '#FAFAF7', '#3B82F6', '#FACC15'],
    htmlPath: 'homepage-layouts/original.html',
    signupPath: 'homepage-layouts/original-signup.html',
  },
  {
    id: 'saas-landing',
    name: 'SaaS Landing',
    description: 'Clean modern SaaS design. Professional, minimal, Inter Tight typography.',
    theme: 'Modern SaaS',
    font: 'Inter Tight',
    colors: ['#0B1220', '#FFFFFF', '#4A80E8', '#E6EAF2'],
    htmlPath: 'homepage-layouts/saas-landing.html',
    signupPath: 'homepage-layouts/saas-signup.html',
  },
  {
    id: 'genz-landing',
    name: 'Gen Z Landing',
    description: 'Bold, expressive design aimed at Gen Z students. High contrast, playful energy.',
    theme: 'Gen Z / bold',
    font: 'Inter',
    colors: ['#0F0F0F', '#F5F0FF', '#7C3AED', '#FF6B6B'],
    htmlPath: 'homepage-layouts/genz-landing.html',
    signupPath: 'homepage-layouts/genz-signup.html',
  },
  {
    id: 'imotive-landing',
    name: 'iMotive Landing',
    description: 'Bold neo-brutalist design. Deep purple + butter yellow palette, Archivo Black display type, hard-shadow cards.',
    theme: 'Neo-brutalist / bold',
    font: 'Archivo Black + Space Grotesk + Inter',
    colors: ['#160a5e', '#fdfbf7', '#6c3aff', '#ffd83d'],
    htmlPath: 'homepage-layouts/imotive-landing.html',
    signupPath: 'homepage-layouts/imotive-signup.html',
  },
  {
    id: 'purple-landing',
    name: 'Purple Landing',
    description: 'Clean modern design with 3D CSS hero visual, dark stats panel, orbit sources diagram, and Space Grotesk typography.',
    theme: 'Modern / clean purple',
    font: 'Space Grotesk + Inter',
    colors: ['#4b00d8', '#ffffff', '#f6f6f8', '#ffd84d'],
    htmlPath: 'homepage-layouts/purple-landing.html',
    signupPath: 'homepage-layouts/purple-signup.html',
  },
];
